// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordledDictionaryApi.Data;

#nullable disable

namespace WordledDictionaryApi.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20251117162103_UpdatedDbContext")]
    partial class UpdatedDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GamesData", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("GamesData");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GuessLogs", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guess")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GuessTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.ToTable("GuessLogs");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.ValidWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ValidWords");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GamesData", b =>
                {
                    b.OwnsOne("WordledDictionaryApi.Models.Entities.WordData", "Word", b1 =>
                        {
                            b1.Property<Guid>("GamesDataGameId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Length")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("string");

                            b1.HasKey("GamesDataGameId");

                            b1.ToTable("GamesData");

                            b1.WithOwner()
                                .HasForeignKey("GamesDataGameId");
                        });

                    b.Navigation("Word")
                        .IsRequired();
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.ValidWord", b =>
                {
                    b.OwnsOne("WordledDictionaryApi.Models.Entities.WordData", "Word", b1 =>
                        {
                            b1.Property<int>("ValidWordId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Length")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("string");

                            b1.HasKey("ValidWordId");

                            b1.ToTable("ValidWords");

                            b1.WithOwner()
                                .HasForeignKey("ValidWordId");
                        });

                    b.Navigation("Word")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
