// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordledDictionaryApi.Data;

#nullable disable

namespace WordledDictionaryApi.Migrations
{
    [DbContext(typeof(DictionaryContext))]
    [Migration("20251115162550_[UpdatedWordModel]")]
    partial class UpdatedWordModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WordledDictionaryApi.Models.DictionaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.DictionaryEntry", b =>
                {
                    b.OwnsOne("WordledDictionaryApi.Models.Word", "Word", b1 =>
                        {
                            b1.Property<int>("DictionaryEntryId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Length")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("string");

                            b1.HasKey("DictionaryEntryId");

                            b1.ToTable("Entries");

                            b1.WithOwner()
                                .HasForeignKey("DictionaryEntryId");
                        });

                    b.Navigation("Word")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
