// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordledDictionaryApi.Data;

#nullable disable

namespace WordledDictionaryApi.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20251123163652_fixforeignkeys")]
    partial class fixforeignkeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GameData", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_turns");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id");

                    b.HasKey("GameId");

                    b.ToTable("GamesData");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GuessLog", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_id");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<string>("Guess")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("guess");

                    b.Property<DateTime>("GuessTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("guess_time");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_correct");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turn");

                    b.HasKey("TransactionId");

                    b.HasIndex("GameId");

                    b.ToTable("GuessLogs");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.ValidWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("ValidWords");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GameData", b =>
                {
                    b.OwnsOne("WordledDictionaryApi.Models.Entities.WordData", "Word", b1 =>
                        {
                            b1.Property<int>("GameDataGameId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Length")
                                .HasColumnType("int")
                                .HasColumnName("word_length");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("string")
                                .HasColumnName("word_value");

                            b1.HasKey("GameDataGameId");

                            b1.ToTable("GamesData");

                            b1.WithOwner()
                                .HasForeignKey("GameDataGameId");
                        });

                    b.Navigation("Word")
                        .IsRequired();
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GuessLog", b =>
                {
                    b.HasOne("WordledDictionaryApi.Models.Entities.GameData", "GameData")
                        .WithMany("GuessLogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameData");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.ValidWord", b =>
                {
                    b.OwnsOne("WordledDictionaryApi.Models.Entities.WordData", "Word", b1 =>
                        {
                            b1.Property<int>("ValidWordId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Length")
                                .HasColumnType("int")
                                .HasColumnName("word_length");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("string")
                                .HasColumnName("word_value")
                                .UseCollation("NOCASE");

                            b1.HasKey("ValidWordId");

                            b1.ToTable("ValidWords");

                            b1.WithOwner()
                                .HasForeignKey("ValidWordId");
                        });

                    b.Navigation("Word")
                        .IsRequired();
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GameData", b =>
                {
                    b.Navigation("GuessLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
