// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordTilesApi.Data;

#nullable disable

namespace WordTilesApi.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WordTilesApi.Models.Entities.GameData", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<string>("GameStatus")
                        .IsRequired()
                        .HasColumnType("string")
                        .HasColumnName("game_status");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_turns");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id");

                    b.HasKey("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GamesData");
                });

            modelBuilder.Entity("WordTilesApi.Models.Entities.GuessLog", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_id");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<string>("Guess")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("guess");

                    b.Property<DateTime>("GuessTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("guess_time");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_correct");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_turns");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turn");

                    b.HasKey("TransactionId");

                    b.HasIndex("GameId");

                    b.ToTable("GuessLogs");
                });

            modelBuilder.Entity("WordTilesApi.Models.Entities.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("WordTilesApi.Models.Entities.ValidWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsSolution")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_solution");

                    b.HasKey("Id");

                    b.ToTable("ValidWords");
                });

            modelBuilder.Entity("WordTilesApi.Models.Entities.GameData", b =>
                {
                    b.HasOne("WordTilesApi.Models.Entities.UserData", "UserData")
                        .WithMany("GameData")
                        .HasForeignKey("PlayerId")
                        .HasPrincipalKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WordTilesApi.Models.Entities.WordData", "Word", b1 =>
                        {
                            b1.Property<int>("GameDataGameId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Length")
                                .HasColumnType("int")
                                .HasColumnName("word_length");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("string")
                                .HasColumnName("word_value");

                            b1.HasKey("GameDataGameId");

                            b1.ToTable("GamesData");

                            b1.WithOwner()
                                .HasForeignKey("GameDataGameId");
                        });

                    b.Navigation("UserData");

                    b.Navigation("Word")
                        .IsRequired();
                });

            modelBuilder.Entity("WordTilesApi.Models.Entities.GuessLog", b =>
                {
                    b.HasOne("WordTilesApi.Models.Entities.GameData", "GameData")
                        .WithMany("GuessLogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameData");
                });

            modelBuilder.Entity("WordTilesApi.Models.Entities.ValidWord", b =>
                {
                    b.OwnsOne("WordTilesApi.Models.Entities.WordData", "Word", b1 =>
                        {
                            b1.Property<int>("ValidWordId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Length")
                                .HasColumnType("int")
                                .HasColumnName("word_length");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("string")
                                .HasColumnName("word_value")
                                .UseCollation("NOCASE");

                            b1.HasKey("ValidWordId");

                            b1.ToTable("ValidWords");

                            b1.WithOwner()
                                .HasForeignKey("ValidWordId");
                        });

                    b.Navigation("Word")
                        .IsRequired();
                });

            modelBuilder.Entity("WordTilesApi.Models.Entities.GameData", b =>
                {
                    b.Navigation("GuessLogs");
                });

            modelBuilder.Entity("WordTilesApi.Models.Entities.UserData", b =>
                {
                    b.Navigation("GameData");
                });
#pragma warning restore 612, 618
        }
    }
}
