// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordledDictionaryApi.Data;

#nullable disable

namespace WordledDictionaryApi.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.DictionaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ValidWords");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GamesData", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("GamesData");
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.DictionaryEntry", b =>
                {
                    b.OwnsOne("WordledDictionaryApi.Models.Entities.Word", "Word", b1 =>
                        {
                            b1.Property<int>("DictionaryEntryId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Length")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("string");

                            b1.HasKey("DictionaryEntryId");

                            b1.ToTable("ValidWords");

                            b1.WithOwner()
                                .HasForeignKey("DictionaryEntryId");
                        });

                    b.Navigation("Word")
                        .IsRequired();
                });

            modelBuilder.Entity("WordledDictionaryApi.Models.Entities.GamesData", b =>
                {
                    b.OwnsOne("WordledDictionaryApi.Models.Entities.Word", "Word", b1 =>
                        {
                            b1.Property<Guid>("GamesDataGameId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Length")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("string");

                            b1.HasKey("GamesDataGameId");

                            b1.ToTable("GamesData");

                            b1.WithOwner()
                                .HasForeignKey("GamesDataGameId");
                        });

                    b.Navigation("Word")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
